**NumPy Arrays**

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.linspace(0, 5, 4)

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(3, 3)

array([[0.61053638, 0.99422186, 0.69513956],
       [0.82318274, 0.898705  , 0.39003879],
       [0.75075693, 0.52177024, 0.44058307]])

In [27]:
np.random.randn(3, 3)

array([[-0.53896486, -0.9145023 , -0.63059725],
       [ 0.16677581, -0.6133578 , -0.67648158],
       [ 0.7631942 , -0.95243844, -0.99051826]])

In [31]:
np.random.randint(1, 100, (3, 3))

array([[69, 85, 34],
       [70, 44, 57],
       [39, 80, 69]])

In [32]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([18, 20, 38, 33, 12, 47, 21,  4, 38, 46])

In [34]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
ranarr.max()

47

In [41]:
ranarr.min()

4

In [42]:
ranarr.argmax()

5

In [43]:
ranarr.argmin()

7

In [45]:
arr.shape

(25,)

In [46]:
arr = arr.reshape(5, 5)
arr.shape

(5, 5)

In [47]:
arr.dtype

dtype('int32')